# Generated by Django 5.1.4 on 2024-12-17 15:42

import converter.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=converter.models.get_unique_upload_path)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InputFileExtension',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OutputParamRangeField',
            fields=[
                ('is_range', models.BooleanField(auto_created=True, default=True, editable=False)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('min', models.SmallIntegerField()),
                ('max', models.SmallIntegerField()),
                ('default', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OutputParamSelectField',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('options', models.JSONField()),
                ('default', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OutputParamBoolField',
            fields=[
                ('is_bool', models.BooleanField(auto_created=True, default=True, editable=False)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('default', models.BooleanField()),
                ('disabled_range_fields_on_enabled', models.ManyToManyField(blank=True, related_name='disabled_range_field_in_enabled_bool_fields', to='converter.outputparamrangefield')),
                ('disabled_select_fields_on_enabled', models.ManyToManyField(blank=True, related_name='disabled_select_field_in_enabled_bool_fields', to='converter.outputparamselectfield')),
            ],
        ),
        migrations.CreateModel(
            name='OutputFormat',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('output_param_bool_fields', models.ManyToManyField(blank=True, related_name='bool_field_in_output_formats', to='converter.outputparamboolfield')),
                ('output_param_range_fields', models.ManyToManyField(blank=True, related_name='range_field_in_output_formats', to='converter.outputparamrangefield')),
                ('output_param_select_fields', models.ManyToManyField(blank=True, related_name='select_field_in_output_formats', to='converter.outputparamselectfield')),
            ],
        ),
        migrations.CreateModel(
            name='UnsupportedTransparencyFormat',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('output_format', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='converter.outputformat')),
            ],
        ),
    ]
